# Generated by Django 4.0.6 on 2022-08-01 00:45

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
