# Generated by Django 4.0.6 on 2022-08-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0003_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='iframe_media',
            field=models.TextField(blank=True, null=True),
        ),
    ]
