# Generated by Django 4.0.6 on 2022-08-21 18:30

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0004_post_iframe_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('section_title', models.CharField(max_length=200)),
                ('section_text', django_quill.fields.QuillField()),
                ('visualization', models.TextField(blank=True, null=True)),
                ('main_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='mobility.post')),
            ],
        ),
    ]
