# Generated by Django 4.0.6 on 2022-08-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0005_subsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='section_title',
        ),
    ]
