# Generated by Django 4.0.6 on 2022-09-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0006_remove_subsection_section_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsection',
            options={'ordering': ['sequence']},
        ),
    ]
